server {
    listen 80;
    server_name localhost;
    
    # Directorio donde pusimos los archivos de Vue compilados
    root /var/www/frontend;
    index index.html;

    # 1. Servir el Frontend (Vue Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # 2. Proxy para la API de Laravel
    location /api {
        alias /var/www/html/public;
        try_files $uri $uri/ @backend;
    }

    # 3. Proxy para Sanctum / Autenticación
    location /sanctum {
        alias /var/www/html/public;
        try_files $uri $uri/ @backend;
    }

    # 4. Redirigir el tráfico dinámico a PHP-FPM
    location @backend {
        rewrite ^/(.*)$ /index.php?/$1 last;
    }

    location ~ \.php$ {
        root /var/www/html/public;
        fastcgi_pass becas_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}